### ISSUE TITLE
“DATASET RELEASE” does not list released datasets in the Helpdesk Portal

### ISSUE THREAD

**Issue by erikhedman** [NBISweden/fega-sweden-helpdesk-acceptance-testing#11] opened 2023-04-04 12:20 UTC
**What I tried to do**
I went to the “DATASET RELEASE” section in order to check the release details of an approved submission.

**What I expected to happen**
As a member of the helpdesk, I expected to see the release details like the status of the release (e.g. “release pending” or “released”, possibly combined with a date). Without information, it is not possible to know what status the dataset has in the release process.

**What actually happened**
I observed that the section was totally empty.

**Steps to reproduce the result**
1. Log in to the **Submitter Portal**
2. Add a new submission
3. Upload a test file and enter required metadata.
4. Click on "FINALISE SUBMISSION"
5. As helpdesk member, log in to the **Helpdesk Portal**
6. Approve the submission
7. Check the release details of the submission under the section “DATASET RELEASE”

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: N/A

**Additional context**
N/A

**Comment by jmenglund** [comment] 2023-05-26 11:33
Approved submissions do appear under dataset release after some time (we don't know how long). The problem is that you don't get information about the status of the submission before it shows up under dataset release.

**Comment by jmenglund** [comment] 2023-05-26 11:35
We close this issue for now, but may want to report this as a feature request some time in the future.

**Closed by jmenglund** 2023-05-26 11:35 UTC
Labels: Type: Bug, Product: Helpdesk Portal, Status: To report
